using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HangUp : MonoBehaviour
{


	public CharacterInput characterInput;

	void OnTriggerEnter (Collider other)
	{
		if (other.gameObject.tag == "Helpers") {
			characterInput.OnCanUpHang (true);
			characterInput.OnUpHangTransform (other.transform);
			characterInput.OnUpHangPosition (other.GetComponent<HangHelpers> ().Positionhelperst);

		}
	}

	void OnTriggerExit (Collider other)
	{
		if (other.gameObject.tag == "Helpers") {
			characterInput.OnCanUpHang (false);
			characterInput.OnUpHangTransform (null);
			characterInput.OnUpHangPosition (other.GetComponent<HangHelpers> ().Positionhelperst);
		}
	}

	void OnTriggerStay (Collider other)
	{
		if (other.gameObject.tag == "Helpers") {
			characterInput.OnCanUpHang (true);
			characterInput.OnUpHangTransform (other.transform);
			characterInput.OnUpHangPosition (other.GetComponent<HangHelpers> ().Positionhelperst);
		}

	}


}
